### ISSUE TITLE
REX Protocol Repo Consolidation

### ISSUE THREAD

**Issue by mikeghen** [Ricochet-Exchange/ricochet-protocol#1]
- All the contracts for REX products are spread across a few places 
- This task involves consolidating it to a single “rex-contracts” repo
- Consolidate all the contracts into a single repository
- Upgrade everything to use ^v0.8.0
- May need to upgrade Superfluid contracts to ^0.8.0

**Comment by josealonso** [comment]
First attempt to consolidate all the contracts into a single repository. The repository name has not been changed yet.
@rashtrakoff and others, please check that he tests for the Rex Markets are still working. I couldn't test it myself, since I don't know how to do the setup for those tests. I recommend using Typescript in the tests.

**Comment by josealonso** [comment]
I forgot to specify which files must be changed inside the *node_modules/@superfluid-finance* directory. I'll try to generate an npm package to install those files.

**Comment by josealonso** [comment]
- npm package created for ricochet contributors to use it instead of having to modify the node_modules directory of the Solidity project. More info ---> https://www.npmjs.com/package/ricochet-exchange-sfcontracts-used
    I tested in my local, following the instructions of the npmjs.com page mentioned above. And it compiles successfully, which makes me think the package is correct.
    I didn't add this new npm dependency to the project, but hopefully I'll do it after the Rex Market version 2 is released.

This Consolidation task is completed now.
